apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: info-app
  template:
    metadata:
      labels:
        app: info-app
    spec:
      containers:
      - name: info-app
        image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
        resources:
          requests:
            memory: "0.25Gi"
            cpu: "250m"
            ephemeral-storage: "128Mi"
          limits:
            memory: "0.25Gi"
            cpu: "250m"
            ephemeral-storage: "128Mi"
        ports:
        - containerPort: 3002
          protocol: TCP
        env:
        - name: GRPC_XDS_BOOTSTRAP
          value: ./cmd/bootstrap.json
        - name: INFO_DB_NAME
          valueFrom:
            secretKeyRef:
              name: info-secret
              key: name
        - name: INFO_DB_USER
          valueFrom:
            secretKeyRef:
              name: user-secret
              key: user
        - name: INFO_DB_PWD
          valueFrom:
            secretKeyRef:
              name: user-secret
              key: pwd
        - name: INFO_DB_HOST
          value: localhost
        - name: INFO_DB_PORT
          value: '5432'
        - name: APP_NAME
          value: Punto y Coma
        - name: INFO_HOST #TODO: UPDATE
          value: localhost
        - name: INFO_PORT
          value: '3002'
      - name: info-cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.0.0.preview.0  # make sure the use the latest version
        resources:
          requests:
            memory: "0.25Gi"
            cpu: "250m"
            ephemeral-storage: "128Mi"
          limits:
            memory: "0.25Gi"
            cpu: "250m"
            ephemeral-storage: "128Mi"
        args:
          # If connecting from a VPC-native GKE cluster, you can use the
          # following flag to have the proxy connect over private IP
          - "--private-ip"
          # Enable structured logging with LogEntry format:
          - "--structured-logs"
          - "--port=5432"
          - "woven-fountain-359423:northamerica-northeast1:modular-pc"
        
        securityContext:
          runAsNonRoot: true

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: info-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: info-app
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

---
apiVersion: v1
kind: Service
metadata:
  name: info-svc
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"3002":{}}}'
spec:
  ports:
  - port: 3002
    name: info-svc
    protocol: TCP
    targetPort: 3002
  selector:
    app: info-app
  type: ClusterIP